(ns gftd.canvas
  "Lean canvas as datoms + append-only event fold (ADR-2607021500 / ADR-2607021600).

   Base (SSoT) = 90-docs/adr/2607021500-portfolio-bmc-lean.datoms.edn.
   The base file is never rewritten by tooling; every edit is an event appended
   to the canvas ledger (gftd.ledger) and folded over the base here.
   Portable .cljc: pure data in the core, io only behind #?(:clj)."
  (:require [clojure.string :as str]
            #?(:clj [clojure.edn :as edn]
               :cljs [cljs.reader :as edn])))

;; ---- base datoms -----------------------------------------------------------

(defn parse-datoms [s] (edn/read-string s))

(defn canvas-block? [d] (contains? d :canvas/id))
(defn hyp? [d] (contains? d :hyp/id))

(defn index
  "datoms vector → {:blocks {canvas-id block-datom} :hyps {hyp-id hyp-datom}
                    :products (sorted set)}"
  [datoms]
  {:blocks   (into {} (comp (filter canvas-block?) (map (juxt :canvas/id identity))) datoms)
   :hyps     (into {} (comp (filter hyp?) (map (juxt :hyp/id identity))) datoms)
   :products (into (sorted-set) (keep :canvas/product) datoms)})

;; ---- event fold ------------------------------------------------------------

(defn apply-event
  "Fold one ledger event into the index. Unknown/observation events are no-ops
   (they are history, not canvas state)."
  [idx e]
  (case (:event/type e)
    :canvas/add-item
    (update-in idx [:blocks (:canvas/id e) :canvas/items] (fnil conj []) (:event/value e))
    :canvas/retract-item
    (update-in idx [:blocks (:canvas/id e) :canvas/items]
               (fn [items] (vec (remove #{(:event/value e)} items))))
    :canvas/note
    (assoc-in idx [:blocks (:canvas/id e) :canvas/note] (:event/value e))
    :hyp/status
    (update-in idx [:hyps (:hyp/id e)] assoc
               :hyp/status (:event/value e)
               :hyp/evidence (:event/evidence e))
    idx))

(defn fold [idx events] (reduce apply-event idx events))

;; ---- product / layer labels --------------------------------------------------

(def layer-labels
  {:llm-inference-infra          "L1 LLM 推論 — infra（Civitai × exo）"
   :llm-inference-app            "L1 LLM 推論 — app（Proton 型）"
   :storage-hosting              "L2 storage hosting（graph BaaS + map / git / search）"
   :business-operator            "L3 business operator（全業種・職種 SaaS + investment platform）"
   :social-network               "L4 social network（atproto SNS）"
   :messenger                    "L4 messenger"
   :adult-creator-platform       "L4 adult creator platform（PornHub / OnlyFans / FANZA 型）"
   :personal-wellbecoming-os     "L5 personal wellbecoming OS"
   :ugc-game-platform            "L6 UGC game / creator platform（Roblox 型）"
   :artificial-organism-platform "L0 artificial organism platform（非営利・公益）"})

(def block-order
  [:lean/problem :lean/customer-segments :lean/uvp :lean/solution :lean/channels
   :lean/revenue-streams :lean/cost-structure :lean/key-metrics :lean/unfair-advantage])

(defn product-blocks [idx product]
  (let [by-block (into {} (map (juxt :canvas/block identity))
                       (filter #(= product (:canvas/product %)) (vals (:blocks idx))))]
    (keep by-block block-order)))

(defn product-hyps [idx product]
  (sort-by :hyp/id (filter #(= product (:hyp/product %)) (vals (:hyps idx)))))

(defn product-layer [idx product]
  (some #(when (= product (:canvas/product %)) (:canvas/layer %)) (vals (:blocks idx))))

;; ---- render ------------------------------------------------------------------

(defn render-md
  "Render one product's lean canvas (post-fold) as markdown.
   opts: {:as-of str}."
  [idx product {:keys [as-of]}]
  (let [layer (product-layer idx product)]
    (str "# " (name product) " — business model / lean canvas\n\n"
         "<!-- generated by gftd cli (70-tools/bmc, ADR-2607021600).\n"
         "     正本 = 90-docs/adr/2607021500-portfolio-bmc-lean.datoms.edn + canvas ledger.\n"
         "     手編集禁止 — `gftd canvas add|retract|note` / `gftd hyp pass|fail` で編集し再生成する。 -->\n\n"
         "**Layer**: " (get layer-labels layer (str layer)) "  \n"
         "**As-of**: " (or as-of "base") "  \n"
         "**Prose 解説**: `90-docs/adr/2607021500-portfolio-seven-layer-business-model-lean-canvas.md`\n\n"
         (apply str
                (for [{:keys [canvas/label canvas/items canvas/note]} (product-blocks idx product)]
                  (str "## " label "\n\n"
                       (apply str (for [i items] (str "- " i "\n")))
                       (when note (str "\n> " note "\n"))
                       "\n")))
         "## Hypotheses\n\n"
         "| id | risk | status | claim | gate | evidence |\n"
         "|---|---|---|---|---|---|\n"
         (apply str
                (for [{:keys [hyp/id hyp/risk hyp/status hyp/claim hyp/gate hyp/evidence]}
                      (product-hyps idx product)]
                  (str "| `" id "` | " (name risk) " | " (name status) " | "
                       claim " | " gate " | " (or evidence "—") " |\n"))))))

(defn render-text
  "Compact terminal rendering of one product's canvas."
  [idx product]
  (str "== " (name product) "  [" (get layer-labels (product-layer idx product)) "]\n"
       (apply str
              (for [{:keys [canvas/id canvas/label canvas/items canvas/note]} (product-blocks idx product)]
                (str "-- " label "  (" id ")\n"
                     (apply str (for [i items] (str "   * " i "\n")))
                     (when note (str "   note: " note "\n")))))
       (apply str
              (for [{:keys [hyp/id hyp/status hyp/claim hyp/gate]} (product-hyps idx product)]
                (str "-- hyp " id " [" (name status) "] " claim "\n   gate: " gate "\n")))))

;; ---- io (clj/bb only) ----------------------------------------------------------

#?(:clj
   (defn load-index
     "Read base datoms file + ledger events (seq) → folded index."
     [base-path events]
     (-> (parse-datoms (slurp base-path))
         index
         (fold events))))
