(ns gftd.score
  "BMC 成熟度 / YC bench 成熟度 scoring (ADR-2607021700).

   2 軸のスコア (0–100):
   - :bmc — business model canvas としての成熟度。canvas 構造から機械判定できる
     3 次元 (completeness / hypothesis / validation) + facts 2 次元 (pricing /
     grounding)。validation は ledger の hyp status から算出されるので、
     `hyp pass|fail` で検証が進むとスコアが動く。
   - :yc — YC bench としての成熟度。net-kotobase GO-TO-MARKET-LEAN-YCBENCH.md の
     基準に整合する design 6 次元 (acute-problem / wedge / tenx / founder-fit /
     distribution / defensibility) 50% + traction 3 次元 (launched / users /
     revenue、重み 2 倍) 50%。

   主観入力 (facts) は 90-docs/business/maturity-facts.edn に日付つきで分離。
   捏造ゼロ: 実測のない次元は低く付ける。全次元 0–5。"
  (:require [clojure.string :as str]
            [gftd.canvas :as canvas]))

;; ---- auto dims (canvas 構造から機械判定) -----------------------------------------

(defn completeness
  "9 block が揃い、平均 item 数が薄くないか。5*(blocks/9)、平均<2 items で -1。"
  [idx product]
  (let [blocks (canvas/product-blocks idx product)
        n (count blocks)
        items (mapcat :canvas/items blocks)
        avg (if (pos? n) (/ (count items) n) 0)]
    (max 0.0 (- (* 5.0 (/ n 9.0)) (if (< avg 2) 1.0 0.0)))))

(defn hypothesis
  "riskiest 仮説が gate つきで定義されているか。gate 無し=2、無定義=0。"
  [idx product]
  (let [hyps (canvas/product-hyps idx product)]
    (cond
      (some #(and (= :riskiest (:hyp/risk %)) (not (str/blank? (str (:hyp/gate %))))) hyps) 5.0
      (seq hyps) 2.0
      :else 0.0)))

(defn validation
  "検証状態 (ledger fold 済の hyp status)。untested=0 / measuring=1.5
   (計器稼働・未到達) / blocked=0 / moot=0 / refuted=2 (学習) /
   validated=5。複数仮説は平均。

   measuring は 2026-07-17 追加: gate が機械測定可能で距離を読み続けている
   状態は untested より前進（計器なしと同じ 0 にするのは不誠実）。validated
   に届かない限り 5 には上げない。"
  [idx product]
  (let [hyps (canvas/product-hyps idx product)
        s {:untested 0.0 :measuring 1.5 :blocked 0.0 :moot 0.0
           :refuted 2.0 :validated 5.0}]
    (if (seq hyps)
      (/ (reduce + (map #(get s (:hyp/status %) 0.0) hyps)) (count hyps))
      0.0)))

;; ---- rubric ------------------------------------------------------------------------

(def bmc-dims
  [[:completeness "9 block 完備・item 濃度" :auto]
   [:hypothesis   "riskiest 仮説 + gate 定義" :auto]
   [:validation   "仮説の検証状態 (ledger)" :auto]
   [:pricing      "価格・単価の確定度" :facts]
   [:grounding    "solution の実装接地度" :facts]])

(def yc-design-dims
  [[:acute-problem "acute problem (切実さ)"]
   [:wedge         "narrow wedge (楔の細さ)"]
   [:tenx          "10x insight"]
   [:founder-fit   "founder-market fit (内需/dogfood)"]
   [:distribution  "distribution (実証された獲得経路)"]
   [:defensibility "defensibility (moat)"]])

(def yc-traction-dims
  [[:launched "launch 段階 (0 idea → 5 scaled)"]
   [:users    "users/traction (external)"]
   [:revenue  "revenue (0 none / 3 first / 5 repeatable)"]])

(defn score-product
  "→ {:bmc {:dims {...} :score 0-100} :yc {:dims {...} :score 0-100}}"
  [idx product facts]
  (let [f (get-in facts [:products product] {})
        bmc-d {:completeness (completeness idx product)
               :hypothesis   (hypothesis idx product)
               :validation   (validation idx product)
               :pricing      (double (get f :pricing 0))
               :grounding    (double (get f :grounding 0))}
        bmc (* 100.0 (/ (reduce + (vals bmc-d)) 25.0))
        design (into {} (for [[k] yc-design-dims] [k (double (get f k 0))]))
        traction (into {} (for [[k] yc-traction-dims] [k (double (get f k 0))]))
        yc (+ (* 50.0 (/ (reduce + (vals design)) 30.0))
              (* 50.0 (/ (reduce + (vals traction)) 15.0)))]
    {:bmc {:dims bmc-d :score bmc}
     :yc  {:dims (merge design traction) :score yc}
     :note (:note f)}))

(defn score-all [idx facts products]
  (into (sorted-map) (for [p products] [p (score-product idx p facts)])))

;; ---- render ------------------------------------------------------------------------

(defn- fmt [x] (let [r (/ (Math/round (* 10.0 x)) 10.0)] (str r)))

(defn render-table
  "terminal / md 共用の markdown table。"
  [scores]
  (str "| product | BMC 成熟度 | YC bench 成熟度 | validation | 主な不足 |\n"
       "|---|---|---|---|---|\n"
       (apply str
              (for [[p {:keys [bmc yc]}] (sort-by (fn [[_ s]] (- (get-in s [:yc :score]))) scores)]
                (let [weak (->> (merge (:dims bmc) (:dims yc))
                                (sort-by val)
                                (take 2)
                                (map (fn [[k v]] (str (name k) "=" (fmt v)))))]
                  (str "| " (name p) " | " (fmt (:score bmc)) " | " (fmt (:score yc))
                       " | " (fmt (get-in bmc [:dims :validation]))
                       " | " (str/join ", " weak) " |\n"))))))

(defn render-md
  [scores facts]
  (str "# portfolio maturity scores — BMC 成熟度 / YC bench 成熟度\n\n"
       "<!-- generated by gftd cli `score md` (70-tools/bmc, ADR-2607021700).\n"
       "     入力 = ADR-2607021500 datoms + canvas ledger + maturity-facts.edn。手編集禁止。 -->\n\n"
       "**As-of**: " (:as-of facts) "  \n"
       "**Rubric**: BMC = completeness/hypothesis/validation(自動) + pricing/grounding(facts)、"
       "各 0–5 → 100 点換算。YC bench = design 6 次元（YCBench 基準: acute-problem/wedge/10x/"
       "founder-fit/distribution/defensibility)50% + traction 3 次元 (launched/users/revenue)50%。\n"
       "**捏造ゼロ**: validation は ledger の hyp status 機械判定（現状ほぼ全滅=0 が正直な値）。\n\n"
       (render-table scores)
       "\n## 次元別詳細\n\n"
       (apply str
              (for [[p {:keys [bmc yc note]}] scores]
                (str "### " (name p) "\n\n"
                     "- BMC: "
                     (str/join ", " (for [[k] bmc-dims] (str (name k) "=" (fmt (get (:dims bmc) k)))))
                     "\n- YC: "
                     (str/join ", " (for [[k] (concat yc-design-dims yc-traction-dims)]
                                      (str (name k) "=" (fmt (get (:dims yc) k)))))
                     (when note (str "\n- note: " note))
                     "\n\n")))))
