use clap::Parser;
use gen_compiler::Compiler;
use gen_parser::parse_statement;
use std::fs;

/// A compiler for the gen language
#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
struct Args {
    /// The input file to compile
    #[arg(required = true)]
    input_file: String,
}

fn main() {
    let args = Args::parse();

    let source_code = match fs::read_to_string(&args.input_file) {
        Ok(code) => code,
        Err(e) => {
            eprintln!("Error reading file {}: {}", args.input_file, e);
            return;
        }
    };

    // 現状のパーサーは単一の文しかパースできないため、
    // 複数行のパースは今後の課題とします。
    // ここでは簡単のため、最初の行のみをパース対象とします。
    let (remaining, statement) = match parse_statement(&source_code) {
        Ok((rem, stmt)) => (rem, stmt),
        Err(e) => {
            eprintln!("Error parsing source code: {:?}", e);
            return;
        }
    };

    if !remaining.trim().is_empty() {
        eprintln!(
            "Warning: could not parse the entire file. Remaining unparsed input: \n'{}'",
            remaining
        );
    }

    let compiler = Compiler::new();
    match compiler.compile(vec![statement]) {
        Ok(rust_code) => {
            println!("// Generated by gen compiler\n");
            println!("// Original file: {}", args.input_file);
            println!("// Note: This is a prototype and only handles a single statement.\n");
            println!("fn main() {{");
            // インデントを追加して出力
            for line in rust_code.lines() {
                println!("    {}", line);
            }
            println!("}}");
        }
        Err(e) => {
            eprintln!("Error compiling code: {}", e);
        }
    }
}
