[package]
name = "kotoba-core"
version = "0.1.0"
edition = "2021"
description = "Core data structures for the kotoba language, based on cubical type theory."
license = "MIT"
repository = "https://github.com/gftdcojp/hottgraph"
homepage = "https://github.com/gftdcojp/hottgraph"
documentation = "https://docs.rs/kotoba-core"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
