export const JUNG_STIMULUS_WORDS = {
  1: { japanese: "頭", english: "head", pronunciation: "あたま" },
  2: { japanese: "緑", english: "green", pronunciation: "みどり" },
  3: { japanese: "水", english: "water", pronunciation: "みず" },
  4: { japanese: "歌う", english: "to sing", pronunciation: "うたう" },
  5: { japanese: "亡くなる", english: "death", pronunciation: "なくなる" },
  6: { japanese: "長い", english: "long", pronunciation: "ながい" },
  7: { japanese: "船", english: "ship", pronunciation: "ふね" },
  8: { japanese: "支払い", english: "to pay", pronunciation: "しはらい" },
  9: { japanese: "窓", english: "window", pronunciation: "まど" },
  10: { japanese: "親切な", english: "friendly", pronunciation: "しんせつ" },
  11: { japanese: "机", english: "table", pronunciation: "つくえ" },
  12: { japanese: "聞く", english: "to ask", pronunciation: "きく" },
  13: { japanese: "村", english: "village", pronunciation: "むら" },
  14: { japanese: "冷たい", english: "cold", pronunciation: "つめたい" },
  15: { japanese: "茎", english: "stem", pronunciation: "きく" },
  16: { japanese: "踊る", english: "to dance", pronunciation: "おどる" },
  17: { japanese: "海", english: "lake", pronunciation: "うみ" },
  18: { japanese: "病気", english: "sick", pronunciation: "びょうき" },
  19: { japanese: "プライド", english: "pride", pronunciation: "プライド" },
  20: { japanese: "料理", english: "to cook", pronunciation: "りょうり" },
  21: { japanese: "インク", english: "ink", pronunciation: "インク" },
  22: { japanese: "怒り", english: "angry", pronunciation: "いかり" },
  23: { japanese: "針", english: "needle", pronunciation: "はり" },
  24: { japanese: "泳ぐ", english: "to swim", pronunciation: "およぐ" },
  25: { japanese: "旅行", english: "journey", pronunciation: "りょこう" },
  26: { japanese: "青い", english: "blue", pronunciation: "あおい" },
  27: { japanese: "電気", english: "lamp", pronunciation: "でんき" },
  28: { japanese: "罪", english: "to sin", pronunciation: "つみ" },
  29: { japanese: "ご飯", english: "bread", pronunciation: "ごはん" },
  30: { japanese: "金持ち", english: "rich", pronunciation: "かねもち" },
  31: { japanese: "木", english: "tree", pronunciation: "き" },
  32: { japanese: "刺す", english: "to prick", pronunciation: "さす" },
  33: { japanese: "同情", english: "pity", pronunciation: "どうじょう" },
  34: { japanese: "黄色", english: "yellow", pronunciation: "きいろ" },
  35: { japanese: "山", english: "mountain", pronunciation: "やま" },
  36: { japanese: "死ぬ", english: "to die", pronunciation: "しぬ" },
  37: { japanese: "塩", english: "salt", pronunciation: "しお" },
  38: { japanese: "新しい", english: "new", pronunciation: "あたらしい" },
  39: { japanese: "癖", english: "custom", pronunciation: "くせ" },
  40: { japanese: "祈る", english: "to pray", pronunciation: "いのる" },
  41: { japanese: "お金", english: "money", pronunciation: "おかね" },
  42: { japanese: "馬鹿", english: "stupid", pronunciation: "ばか" },
  43: { japanese: "ノート", english: "exercise-book", pronunciation: "ノート" },
  44: { japanese: "軽蔑", english: "to despise", pronunciation: "けいべつ" },
  45: { japanese: "指", english: "finger", pronunciation: "ゆび" },
  46: { japanese: "高価な", english: "dear", pronunciation: "こうかな" },
  47: { japanese: "鳥", english: "bird", pronunciation: "とり" },
  48: { japanese: "落ちる", english: "to fall", pronunciation: "おちる" },
  49: { japanese: "本", english: "book", pronunciation: "ほん" },
  50: { japanese: "不正", english: "unjust", pronunciation: "ふせい" },
  51: { japanese: "蛙", english: "frog", pronunciation: "かえる" },
  52: { japanese: "別れる", english: "to part", pronunciation: "わかれる" },
  53: { japanese: "空腹", english: "hunger", pronunciation: "くうふく" },
  54: { japanese: "白い", english: "white", pronunciation: "しろい" },
  55: { japanese: "子供", english: "child", pronunciation: "こども" },
  56: { japanese: "注意", english: "to pay attention", pronunciation: "ちゅうい" },
  57: { japanese: "鉛筆", english: "pencil", pronunciation: "えんぴつ" },
  58: { japanese: "悲しい", english: "sad", pronunciation: "かなしい" },
  59: { japanese: "りんご", english: "plum", pronunciation: "りんご" },
  60: { japanese: "結婚", english: "to marry", pronunciation: "けっこん" },
  61: { japanese: "家", english: "house", pronunciation: "いえ" },
  62: { japanese: "かわいい", english: "darling", pronunciation: "かわいい" },
  63: { japanese: "ガラス", english: "glass", pronunciation: "ガラス" },
  64: { japanese: "争う", english: "to quarrel", pronunciation: "あらそう" },
  65: { japanese: "毛皮", english: "fur", pronunciation: "けがわ" },
  66: { japanese: "大きい", english: "big", pronunciation: "おおきい" },
  67: { japanese: "人参", english: "carrot", pronunciation: "にんじん" },
  68: { japanese: "塗る", english: "to paint", pronunciation: "ぬる" },
  69: { japanese: "部分", english: "part", pronunciation: "ぶぶん" },
  70: { japanese: "古い", english: "old", pronunciation: "ふるい" },
  71: { japanese: "花", english: "flower", pronunciation: "はな" },
  72: { japanese: "打つ", english: "to beat", pronunciation: "うつ" },
  73: { japanese: "箱", english: "box", pronunciation: "はこ" },
  74: { japanese: "荒い", english: "wild", pronunciation: "あらい" },
  75: { japanese: "家族", english: "family", pronunciation: "かぞく" },
  76: { japanese: "洗う", english: "to wash", pronunciation: "あらう" },
  77: { japanese: "牛", english: "cow", pronunciation: "うし" },
  78: { japanese: "変", english: "friend （誤訳？）", pronunciation: "へん" },
  79: { japanese: "幸運", english: "happiness", pronunciation: "こううん" },
  80: { japanese: "嘘", english: "lie", pronunciation: "うそ" },
  81: { japanese: "礼儀", english: "deportment", pronunciation: "れいぎ" },
  82: { japanese: "狭い", english: "narrow", pronunciation: "せまい" },
  83: { japanese: "兄弟", english: "brother", pronunciation: "きょうだい" },
  84: { japanese: "怖がる", english: "to fear", pronunciation: "こわがる" },
  85: { japanese: "コウノトリ", english: "stork", pronunciation: "こうのとり" },
  86: { japanese: "間違い", english: "FALSE", pronunciation: "まちがい" },
  87: { japanese: "心配", english: "anxiety", pronunciation: "しんぱい" },
  88: { japanese: "キス", english: "to kiss", pronunciation: "キス" },
  89: { japanese: "花嫁", english: "bride", pronunciation: "はなよめ" },
  90: { japanese: "純粋な", english: "pure", pronunciation: "じゅんすいな" },
  91: { japanese: "ドア", english: "door", pronunciation: "ドア" },
  92: { japanese: "選ぶ", english: "to choose", pronunciation: "えらぶ" },
  93: { japanese: "干し草", english: "hay", pronunciation: "ほしくさ" },
  94: { japanese: "嬉しい", english: "contented", pronunciation: "うれしい" },
  95: { japanese: "虐める", english: "ridicule", pronunciation: "いじめる" },
  96: { japanese: "眠る", english: "to sleep", pronunciation: "ねむる" },
  97: { japanese: "年月", english: "month", pronunciation: "ねんげつ" },
  98: { japanese: "きれいな", english: "nice", pronunciation: "きれいな" },
  99: { japanese: "女", english: "woman", pronunciation: "おんな" },
  100: { japanese: "侮辱", english: "to abuse", pronunciation: "ぶじょく" },
};


export const JUNG_TEST_WELCOME_MESSAGE = `
  ユングの言語連想検査へようこそ。この検査は、あなたの「言葉」に対する心理的な連想を探るものです。私が単語を提示しますので、最初に思いついた単語で応答してください。１つの単語に対して、2秒以内を目安に回答してください。回答があった時点で次の単語が提示されます。10秒が過ぎた場合は次の単語が提示されます。セッションは２回行われ、一回のセッションで単語は100個提示されます。
`;
