use clap::Parser;
use kotoba_compiler::Compiler;
use kotoba_parser::parse_statement;
use std::fs;

/// `kotoba`言語のコンパイラ
#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
struct Args {
    /// コンパイル対象の`.gen`ファイル
    #[arg(required = true)]
    input_file: String,
}

fn main() {
    let args = Args::parse();

    let source_code = match fs::read_to_string(&args.input_file) {
        Ok(code) => code,
        Err(e) => {
            eprintln!("ファイル読み込みエラー {}: {}", args.input_file, e);
            return;
        }
    };

    // TODO: 将来的には複数の文をパースできるようにする
    let (remaining, statement) = match parse_statement(&source_code) {
        Ok((rem, stmt)) => (rem, stmt),
        Err(e) => {
            eprintln!("構文解析エラー: {:?}", e);
            return;
        }
    };

    if !remaining.trim().is_empty() {
        eprintln!(
            "警告: ファイルのすべてを解析できませんでした。未解析の残り: \n'{}'",
            remaining
        );
    }

    let compiler = Compiler::new();
    match compiler.compile(vec![statement]) {
        Ok(rust_code) => {
            println!("// Generated by gen compiler from: {}", args.input_file);
            println!("// このコードはプロトタイプであり、まだ完全ではありません。\n");

            // --- ダミーの型定義 ---
            println!("// ダミーの型定義: 本来は`kotoba-std`のような標準ライブラリで提供される");
            println!("type 間 = ();");
            println!("type i64 = i64;");
            println!("trait AsEn {{ fn as_en(&self) -> Self; }}");
            println!("impl AsEn for kotoba_core::Ba {{ fn as_en(&self) -> Self {{ self.clone() }} }}");
            println!("#[derive(Clone)] struct 縁<I, O>(std::marker::PhantomData<(I, O)>);");
            println!("fn pipe<T, U, V>(_: T, _: U) -> V {{ panic!() }}");
            println!("");
            // --- ここまで ---

            println!("fn main() {{");
            println!("    // ダミーの変数定義");
            println!("    let ticks: 縁<間, i64> = unimplemented!();");
            println!("    let doubler: 縁<i64, i64> = unimplemented!();");
            println!("");

            for line in rust_code.lines() {
                if !line.trim().is_empty() {
                    println!("    {}", line);
                }
            }

            println!("}}");
        }
        Err(e) => {
            eprintln!("コンパイルエラー: {}", e);
        }
    }
}
