use clap::Parser as ClapParser;
use kotoba_compiler::Compiler;
use std::fs;

/// `kotoba`言語のコンパイラ
#[derive(ClapParser, Debug)]
#[command(version, about, long_about = None)]
struct Args {
    /// コンパイル対象の`.kotoba`ファイル
    #[arg(required = true)]
    input_file: String,
}

fn main() {
    let args = Args::parse();

    let source_code = match fs::read_to_string(&args.input_file) {
        Ok(code) => code,
        Err(e) => {
            eprintln!("ファイル読み込みエラー {}: {}", args.input_file, e);
            return;
        }
    };

    let program = match kotoba_parser::parse_program(&source_code) {
        Ok(statements) => statements,
        Err(e) => {
            eprintln!("構文解析エラー: {:?}", e);
            return;
        }
    };

    let mut compiler = Compiler::new();
    match compiler.compile(program) {
        Ok(rust_code) => {
            println!("// Generated by kotoba compiler from: {}\n", args.input_file);
            println!("use kotoba_core;");
            println!("{}", rust_code);
        }
        Err(e) => {
            eprintln!("コンパイルエラー: {}", e);
        }
    }
}
