#!/usr/bin/env bb
;; gen-west-manifest.bb
;; manifest/repos.edn(ポリシー)+ git の事実(working HEAD)から manifest/west.yml を生成。
;;
;;   ポリシー(remote/既定/group-filter/DataLad/B2)は manifest/repos.edn。
;;   project 一覧と pin は git から採る:
;;     - パス: 既存 west.yml の `path:` 群、無ければ superproject の gitlink(初回)。
;;     - revision: 各 project の working tree HEAD(pin 前進に自動追従)。
;;
;; DataLad dataset(:datalad)は west project にしつつ `datalad` グループへ隔離し
;; userdata に印を付ける(実体取得は `west annex-get`)。
;;
;; 使い方:
;;   bb scripts/gen-west-manifest.bb            ; west.yml を更新
;;   bb scripts/gen-west-manifest.bb --check    ; 差分があれば exit 1(CI 用)

(require '[clojure.string :as str]
         '[clojure.edn :as edn]
         '[clojure.java.shell :refer [sh]]
         '[clojure.java.io :as io])

(def root (-> (sh "git" "rev-parse" "--show-toplevel") :out str/trim))
(def manifest-dir (io/file root "manifest"))
(def out-file (io/file manifest-dir "west.yml"))
(def cfg (edn/read-string (slurp (io/file manifest-dir "repos.edn"))))

(defn paths-from-west-yml []
  (when (.exists out-file)
    (->> (str/split-lines (slurp out-file))
         (keep #(second (re-find #"^\s*path:\s*(\S+)" %))))))

(defn projects-from-west-yml []
  (when (.exists out-file)
    (let [entries (atom {})
          current (atom nil)]
      (doseq [line (str/split-lines (slurp out-file))]
        (when-let [name (second (re-find #"^\s*- name:\s*(\S+)" line))]
          (reset! current {:name name}))
        (when @current
          (when-let [revision (second (re-find #"^\s*revision:\s*(\S+)" line))]
            (swap! current assoc :revision revision))
          (when-let [path (second (re-find #"^\s*path:\s*(\S+)" line))]
            (swap! current assoc :path path))
          (when (re-find #"^\s*submodules:\s*true\s*$" line)
            (swap! current assoc :submodules true))
          (when-let [path (:path @current)]
            (swap! entries assoc path @current))))
      @entries)))

(defn paths-from-gitlinks []
  (->> (:out (sh "git" "ls-tree" "-r" "HEAD"))
       str/split-lines
       (keep (fn [l] (when (str/includes? l " commit ")
                       (-> (str/split l #"\t" 2) second))))))

(defn working-head [path]
  (let [{:keys [exit out]} (sh "git" "-C" (str (io/file root path)) "rev-parse" "HEAD")]
    (when (zero? exit) (str/trim out))))

(defn org-of  [p] (second (str/split p #"/")))
(defn name-of [p] (last (str/split p #"/")))
(defn nested? [p] (.exists (io/file root p ".gitmodules")))
(defn remote-of [p] (get (:remote-overrides cfg) p (org-of p)))
(defn canonical-path [p] (get (:path-overrides cfg) p p))
(defn heavy? [p] (contains? (:heavy cfg) p))
(defn dup-basenames [paths]
  (->> paths (map name-of) frequencies (keep (fn [[n c]] (when (> c 1) n))) set))
(defn west-name [path dup-names]
  (let [n (name-of path)]
    (if (contains? dup-names n) (str (org-of path) "-" n) n)))

(def existing-projects (projects-from-west-yml))

(defn project-entry [path dup-names]
  (let [existing (get existing-projects path)
        sha     (or (working-head path) (:revision existing))
        dl      (get-in cfg [:datalad path])
        depth   (when (heavy? path) (get-in cfg [:defaults :clone-depth]))
        groups  (if dl [(:group dl)] [(org-of path)])
        recurse (or (contains? (:force-recurse-submodules cfg) path)
                    (nested? path)
                    (:submodules existing))]
    (when sha
      (str "    - name: " (west-name path dup-names) "\n"
           "      remote: " (remote-of path) "\n"
           "      revision: " sha "\n"
           "      path: " path "\n"
           (when depth (str "      clone-depth: " depth "\n"))
           "      groups: [" (str/join ", " groups) "]\n"
           (when recurse "      submodules: true\n")
           (when dl (str "      userdata:\n"
                         "        datalad: true\n"
                         "        annex-remote: " (:annex-remote dl) "\n"))))))

(defn render []
  (let [paths (->> (concat (or (seq (paths-from-west-yml)) (paths-from-gitlinks))
                           (:extra-projects cfg))   ; repos.edn の新規追加口を union
                   (filter #(str/starts-with? % "orgs/"))
                   (map canonical-path)
                   distinct sort)
        dups  (dup-basenames paths)]
    (str
     "# west.yml — generated by scripts/gen-west-manifest.bb. DO NOT EDIT BY HAND.\n"
     "# source of truth: manifest/repos.edn  /  再生成: bb scripts/gen-west-manifest.bb\n"
     "manifest:\n  version: \"1.0\"\n\n  remotes:\n"
     (apply str (for [[n u] (sort (:remotes cfg))]
                  (str "    - name: " n "\n      url-base: " u "\n")))
     "\n  defaults:\n    revision: " (get-in cfg [:defaults :revision]) "\n\n"
     "  group-filter: [" (str/join ", " (:group-filter cfg)) "]\n\n"
     "  projects:\n"
     (apply str (keep #(project-entry % dups) paths))
     "\n  self:\n    path: manifest\n    west-commands: west-commands.yml\n")))

(let [content (render)
      check?  (some #{"--check"} *command-line-args*)]
  (if check?
    (if (= (when (.exists out-file) (slurp out-file)) content)
      (do (println "west.yml is up to date.") (System/exit 0))
      (do (binding [*out* *err*] (println "west.yml is STALE. run: bb scripts/gen-west-manifest.bb"))
          (System/exit 1)))
    (do (.mkdirs manifest-dir)
        (spit out-file content)
        (println (str "wrote " (.getPath out-file)
                      " (" (count (re-seq #"path: orgs/" content)) " projects)")))))
