#!/usr/bin/env nbb
;; gen-orgs-gitignore.cljs
;; manifest/west.yml の `path:` 群から .gitignore の生成ブロックを作る。
;;
;; なぜ必要か（2026-07-25 cleanup で判明）:
;;   west checkout（orgs/<org>/<repo>）は superproject の tracked content ではない
;;   ので、ignore していないと `git status` に `??` として出る。実測 1,922 件が
;;   ignore も tracked もされておらず（`git status` 上は親ディレクトリに折り畳まれて
;;   123 行に見えていた）、この巨大なノイズの中に本物の orphan が埋もれていた。
;;   ノイズ源はここまで手書き allowlist（`/orgs/kotoba-lang/aml/` 等 23 行）で
;;   場当たり的に潰されてきたが、west に登録するたび手で足す運用は破綻している。
;;
;; 設計:
;;   **登録済み = ignore（静か） / 未登録 = `git status` に出る（signal）** という
;;   対応にする。west.yml の path 集合ちょうどを ignore するので、orphan は構造的に
;;   隠れない — scripts/west-orphan-audit.cljs の findings が `git status` にも
;;   そのまま浮かぶ。
;;
;;   ブロックは **純粋に追記的**。既存の手書き行は一切消さない（west path と
;;   重複する行が残っても gitignore では無害）。
;;
;; 使い方:
;;   nbb scripts/gen-orgs-gitignore.cljs            ; .gitignore を更新
;;   nbb scripts/gen-orgs-gitignore.cljs --check    ; 差分があれば exit 1（CI 用）
;;
;; 注意: tracked file には gitignore は効かない（git の仕様）。superproject に
;; 誤って commit された west checkout は、この生成ブロックでは静かにならない —
;; それは index から外す別問題（.gitignore 内の "pre-west-migration gitlink"
;; コメント群がその履歴）。

(require '[scripts.nbb-compat :as io :refer [slurp spit sh]]
         '[clojure.string :as str])

(def root (-> (sh "git" "rev-parse" "--show-toplevel") :out str/trim))
(def west-file (io/file root "manifest" "west.yml"))
(def gitignore-file (io/file root ".gitignore"))

(def begin-marker
  "# >>> BEGIN generated by scripts/gen-orgs-gitignore.cljs — DO NOT EDIT BY HAND >>>")
(def end-marker
  "# <<< END generated by scripts/gen-orgs-gitignore.cljs <<<")

(def header
  ["# west-managed project checkouts (manifest/west.yml). 実体は GitHub にあり、"
   "# superproject の tracked content ではないので ignore する。"
   "#"
   "# 登録済み = ここで ignore（git status が静か） / 未登録 = git status に `??` で出る。"
   "# この対応を壊さないこと — 未登録 orphan が見えることが"
   "# scripts/west-orphan-audit.cljs と対になる検出シグナルになっている。"
   "#"
   "# 再生成: nbb scripts/gen-orgs-gitignore.cljs（--check で CI 検証）"])

(defn west-paths
  "west.yml から `      path: orgs/...` を拾って sort-unique した seq。"
  []
  (->> (str/split-lines (slurp west-file))
       (keep (fn [line]
               (let [t (str/trim line)]
                 (when (str/starts-with? t "path: ")
                   (let [p (str/trim (subs t (count "path: ")))]
                     (when (str/starts-with? p "orgs/") p))))))
       distinct
       sort))

(defn block
  "生成ブロックの行 seq（marker 込み）。"
  [paths]
  (concat [begin-marker] header (map #(str "/" % "/") paths) [end-marker]))

(defn splice
  "既存 .gitignore 行に生成ブロックを差し込む。marker があれば置換、無ければ末尾に追記。"
  [lines blk]
  (let [b (.indexOf (vec lines) begin-marker)
        e (.indexOf (vec lines) end-marker)]
    (if (and (>= b 0) (> e b))
      (concat (take b lines) blk (drop (inc e) lines))
      ;; 末尾追記。直前に空行を1つだけ置く。
      (concat (->> lines reverse (drop-while str/blank?) reverse) [""] blk))))

(defn -main [& args]
  (let [check? (contains? (set args) "--check")
        paths  (west-paths)
        _      (when (empty? paths)
                 (println "ERROR: manifest/west.yml から path: を1件も拾えなかった（生成中止）")
                 (js/process.exit 2))
        cur    (str/split-lines (slurp gitignore-file))
        next-l (splice cur (block paths))
        cur-s  (str (str/join "\n" cur) "\n")
        next-s (str (str/join "\n" next-l) "\n")]
    (cond
      (= cur-s next-s)
      (println (str "OK: .gitignore は canonical（west paths " (count paths) " 件）"))

      check?
      (do (println (str "STALE: .gitignore が west.yml と一致しない（west paths "
                        (count paths) " 件）。"
                        "`nbb scripts/gen-orgs-gitignore.cljs` で再生成せよ"))
          (js/process.exit 1))

      :else
      (do (spit gitignore-file next-s)
          (println (str "wrote .gitignore（west paths " (count paths) " 件、"
                        (count cur) " → " (count next-l) " 行）"))))))

(apply -main *command-line-args*)
