#!/usr/bin/env bb
;; gen-west-manifest.bb
;; west.yml を生成/更新する。
;;
;; 各 project の revision は「その working tree の HEAD」をピンする。
;;   - これにより pin の前進（submodule の checkout を進めた状態）に自動追従する。
;;   - 移行後（gitlink 撤去後）も gitlink に依存せず動作する。
;; project パスの探索元:
;;   - 既存 west.yml があればその `path:` 群（= 既に west 管理対象の集合）
;;   - 無ければ superproject の gitlink（初回ブートストラップ）
;; EXCLUDE-PATHS は west 管理から外す（ローカル未コミット/未push 等で reconcile 待ち）。
;;
;; 使い方:
;;   bb scripts/gen-west-manifest.bb            ; west.yml を更新
;;   bb scripts/gen-west-manifest.bb --check    ; 差分があれば exit 1（CI 用）

(require '[clojure.string :as str]
         '[clojure.java.shell :refer [sh]]
         '[clojure.java.io :as io])

(def root (-> (sh "git" "rev-parse" "--show-toplevel") :out str/trim))
;; west のトポロジ: topdir = superproject ルート, manifest repo = サブディレクトリ。
;; projects は orgs/... = 現 submodule と同一パスに展開され、チェックアウト名に依存しない。
(def manifest-dir (io/file root "manifest"))
(def out-file (io/file manifest-dir "west.yml"))

;; west 管理から除外するパス（git submodule のまま温存。reconcile/push 後に戻す）。
(def exclude-paths
  #{"orgs/etzhayyim/root"           ; ローカル分岐(7504/101)+ dirty・未push
    "orgs/gftdcojp/network-isekai"  ; 10 behind・dirty(未コミット作業)
    "orgs/gftdcojp/m365-archive"})  ; DataLad dataset(別管理)

;; org -> west remote 定義（url-base と名前）
(def remotes
  [{:name "com-junkawasaki" :url-base "git@github.com:com-junkawasaki"}
   {:name "gftdcojp"        :url-base "git@github.com:gftdcojp"}
   {:name "etzhayyim"       :url-base "https://github.com/etzhayyim"}])

(defn paths-from-west-yml []
  (when (.exists out-file)
    (->> (str/split-lines (slurp out-file))
         (keep (fn [l] (second (re-find #"^\s*path:\s*(\S+)" l)))))))

(defn paths-from-gitlinks []
  (->> (:out (sh "git" "ls-tree" "-r" "HEAD"))
       str/split-lines
       (keep (fn [line]
               (when (str/includes? line " commit ")
                 (-> (str/split line #"\t" 2) second))))))

(defn working-head [path]
  (let [{:keys [exit out]} (sh "git" "-C" (str (io/file root path)) "rev-parse" "HEAD")]
    (when (zero? exit) (str/trim out))))

(defn org-of [path] (second (str/split path #"/")))
(defn name-of [path] (last (str/split path #"/")))
(defn has-nested-submodules? [path] (.exists (io/file root path ".gitmodules")))

(defn project-entry [path]
  (let [sha (working-head path)]
    (when sha
      (str "    - name: " (name-of path) "\n"
           "      remote: " (org-of path) "\n"
           "      revision: " sha "\n"
           "      path: " path "\n"
           "      clone-depth: 1\n"
           "      groups: [" (org-of path) "]\n"
           (when (has-nested-submodules? path) "      submodules: true\n")))))

(defn remote-block [{:keys [name url-base]}]
  (str "    - name: " name "\n      url-base: " url-base "\n"))

(defn render []
  (let [paths (->> (or (seq (paths-from-west-yml)) (paths-from-gitlinks))
                   (filter #(str/starts-with? % "orgs/"))
                   (remove exclude-paths)
                   distinct
                   sort)]
    (str
     "# west.yml — generated by scripts/gen-west-manifest.bb. DO NOT EDIT BY HAND.\n"
     "# 再生成: bb scripts/gen-west-manifest.bb\n"
     "# revision は各 working tree の HEAD をピン。除外パスは scripts 内 exclude-paths を参照。\n"
     "manifest:\n"
     "  version: \"1.0\"\n\n"
     "  remotes:\n"
     (apply str (map remote-block remotes))
     "\n  defaults:\n"
     "    revision: main\n\n"
     "  # org 単位でグループ化（west update --group-filter で選択取得できる）\n"
     "  group-filter: [+com-junkawasaki, +gftdcojp, +etzhayyim]\n\n"
     "  projects:\n"
     (apply str (keep project-entry paths))
     "\n  self:\n"
     "    path: manifest\n")))

(let [content (render)
      check?  (some #{"--check"} *command-line-args*)]
  (if check?
    (if (= (when (.exists out-file) (slurp out-file)) content)
      (do (println "west.yml is up to date.") (System/exit 0))
      (do (binding [*out* *err*] (println "west.yml is STALE. run: bb scripts/gen-west-manifest.bb"))
          (System/exit 1)))
    (do (.mkdirs manifest-dir)
        (spit out-file content)
        (println (str "wrote " (.getPath out-file)
                      " (" (count (re-seq #"path: orgs/" content)) " projects)")))))
