#!/usr/bin/env nbb
(ns verify-kotoba-source-census
  "`.kotoba` files that are not Kotoba source, and repositories where both
  kinds sit under the same extension.

  ## The failure this exists for

  Measured 2026-08-19 across 4,459 west checkouts: 2,044 tracked `.kotoba`
  files, of which **988 are a legacy C-shaped schema DSL** generated by
  `deepen_actors.py` and 1,019 are Kotoba source. The extension does not
  distinguish them, so anything that keys on it -- a count, a grep, a build
  glob, a migration progress report -- silently conflates a language corpus
  with a data corpus that is roughly the same size.

  `kotoba-lang/kotoba-lang`'s `lang/q9-migration.edn` already named this in
  July (`:legacy-schema-dsl-extension-collision`, 853 of 1,052 then) and
  stated the rule: only canonical Clojure-shaped Kotoba source may use the
  bare `.kotoba` extension. What was missing was anything that measures it,
  so the total kept being read as migration progress. ADR-2608191000
  recorded the first census by hand; this makes it repeatable.

  ## What it reports

  A census, then findings. The census is printed every run so drift is
  visible even when nothing is newly wrong.

  - `collision` -- ONE finding carrying the legacy-DSL count. It is one
    finding and not 988 because the condition is known, named and at scale;
    988 keys would be noise and could not be accepted or cleared as a unit.
  - `mixed:<org>/<repo>` -- a repository holding more than one shape under
    the extension. This is where a tool actually conflates them, because a
    per-repo glob cannot separate the two. Measured: 4 repositories.
  - `shape:<path>` -- a `.kotoba` file that is neither Kotoba source nor the
    known legacy DSL: EDN data (25), unrecognised (7), empty or comment-only
    (5). These are individually fixable, so they are individually keyed.

  ## How a file is classified, stated because the census depends on it

  Strip leading blank lines, `;;` comments and `//` comments, then look at
  the first remaining character:

      (            -> :kotoba-source
      { or [       -> :edn-data
      namespace/entity/} -> :legacy-dsl
      nothing left -> :empty-or-comment-only
      anything else-> :unknown

  A first attempt used `head -40` and matched `^\\(ns ` or `^\\(defn `. It
  called 986 files source. It was wrong in both directions: 18 files with
  long `;;` headers pushed the first form past line 40, and it could not see
  the EDN-data class at all. The rule above is why the number moved to
  1,019, and it is stated here so the next person can tell a real change
  from a reclassification.

  ## What it counts, and what it does not

  Tracked files only (`git ls-files` per checkout). The working tree holds
  2,346, the difference being untracked. Neither number is wrong; a census
  that does not say which one it took is. ADR-2608191000 records a third
  figure, 4,189, that reconciles with neither and whose method is unstated.

  ## Refusing to answer

  Zero checkouts or zero `.kotoba` files is not a clean workspace, it is a
  detector pointed at the wrong tree. Both exit 2."
  (:require ["child_process" :as cp]
            ["fs" :as fs]
            ["path" :as p]
            [clojure.string :as str]))

(def argv (vec *command-line-args*))
(def root (or (first (remove #(str/starts-with? % "--") argv)) "."))
(def report? (some #{"--report"} argv))

(defn- die-unanswered [msg]
  (println (str "UNANSWERED\t" msg))
  (js/process.exit 2))

(defn- orgs-dir [] (p/join root "orgs"))

(defn- checkouts []
  (let [o (orgs-dir)]
    (when-not (fs/existsSync o) (die-unanswered (str "no orgs/ under " root)))
    (for [org (sort (fs/readdirSync o))
          :let [od (p/join o org)]
          :when (.isDirectory (fs/statSync od))
          repo (sort (fs/readdirSync od))
          :let [rd (p/join od repo)]
          :when (fs/existsSync (p/join rd ".git"))]
      rd)))

(defn- tracked-kotoba
  "One shell pipeline rather than 4,459 sequential spawns: measured 3m20s
  sequential against 52s at -P16 on this machine."
  [dirs]
  (let [list-file (p/join (or js/process.env.TMPDIR "/tmp")
                          (str "kotoba-census-" (.-pid js/process) ".txt"))]
    (fs/writeFileSync list-file (str/join "\n" dirs))
    (try
      (let [out (cp/execSync
                 ;; -S 65536: BSD xargs caps -I replacement at 255 bytes by
                 ;; default and substitutes {} twice here, so a long checkout
                 ;; path fails with "command line cannot be assembled, too
                 ;; long". Measured on this machine against a scratchpad tree.
                 (str "xargs -P 16 -S 65536 -I{} "
                      "sh -c 'git -C {} ls-files \"*.kotoba\" 2>/dev/null "
                      "| sed \"s#^#{}/#\"' < " list-file)
                 #js {:maxBuffer (* 64 1024 1024) :encoding "utf8"})]
        (remove str/blank? (str/split-lines out)))
      (catch :default e
        ;; An enumeration that could not run is NOT a finding. Exiting 1 here
        ;; would be indistinguishable from "the workspace has defects", which
        ;; is the failure class ADR-2608136000 names.
        (die-unanswered (str "could not enumerate tracked .kotoba files: "
                             (.-message e))))
      (finally (when (fs/existsSync list-file) (fs/unlinkSync list-file))))))

(defn classify
  "Exported shape rule. See the namespace docstring for why it is this and
  not a line-bounded regex."
  [text]
  (let [first-form (->> (str/split-lines text)
                        (remove #(re-matches #"\s*(;;.*|//.*)?" %))
                        first)]
    (cond
      (nil? first-form)                          :empty-or-comment-only
      (re-find #"^\s*\(" first-form)             :kotoba-source
      (re-find #"^\s*[\{\[]" first-form)         :edn-data
      (re-find #"^\s*(namespace |entity |\})" first-form) :legacy-dsl
      :else                                      :unknown)))

(defn- repo-of [path]
  (let [segs (str/split path #"/")
        i (.indexOf (into-array segs) "orgs")]
    (when (and (>= i 0) (> (count segs) (+ i 2)))
      (str (nth segs (inc i)) "/" (nth segs (+ i 2))))))

(defn -main []
  (let [dirs (vec (checkouts))
        _ (when (zero? (count dirs))
            (die-unanswered (str "0 checkouts under " (orgs-dir))))
        files (vec (tracked-kotoba dirs))
        _ (when (zero? (count files))
            (die-unanswered (str (count dirs) " checkouts hold no tracked .kotoba file")))
        rows (for [f files]
               {:path f
                :repo (repo-of f)
                :class (classify (try (fs/readFileSync f "utf8") (catch :default _ "")))})
        rows (vec rows)
        census (frequencies (map :class rows))
        legacy (get census :legacy-dsl 0)
        odd (filter #(#{:edn-data :unknown :empty-or-comment-only} (:class %)) rows)
        mixed (->> rows
                   (group-by :repo)
                   (filter (fn [[r xs]] (and r (> (count (set (map :class xs))) 1))))
                   (map first)
                   sort)]
    (if report?
      (println (js/JSON.stringify (clj->js {:checkouts (count dirs)
                                            :files (count files)
                                            :census census})))
      (do
        (println (str "SCANNED\t" (count files) "\ttracked .kotoba files across "
                      (count dirs) " checkouts"))
        (println (str "CENSUS\t"
                      (str/join "\t" (for [k [:kotoba-source :legacy-dsl :edn-data
                                              :unknown :empty-or-comment-only]]
                                       (str (name k) "=" (get census k 0))))))
        (when (pos? legacy)
          (println (str "FINDING\tfail\tcollision\t" legacy
                        " .kotoba files are the legacy schema DSL, not Kotoba source."
                        " Any count keyed on the extension conflates them with the "
                        (get census :kotoba-source 0) " that are.")))
        (doseq [r mixed]
          (println (str "FINDING\tfail\tmixed:" r
                        "\tholds more than one shape under .kotoba, so a per-repo glob"
                        " cannot separate source from data")))
        (doseq [{:keys [path class]} (sort-by :path odd)]
          (println (str "FINDING\twarn\tshape:" path "\tis " (name class)
                        ", not Kotoba source, but uses the bare .kotoba extension")))
        (println)
        (let [n (+ (if (pos? legacy) 1 0) (count mixed) (count odd))]
          (if (pos? n)
            (do (println (str n " finding(s): " (count mixed) " mixed-shape repo(s), "
                              (count odd) " off-shape file(s)"
                              (when (pos? legacy) (str ", and the ") )
                              (when (pos? legacy) (str legacy "-file legacy DSL collision"))))
                (js/process.exit 1))
            (println (str "OK — all " (count files)
                          " tracked .kotoba files are Kotoba source."))))))))

(-main)
