name: 【デプロイ】検証サーバーへデプロイ

on:
    workflow_dispatch:

########################################################
# ！注意 このワークフローを使うには以下のSecretsが必要です！
########################################################
# STG_SSH_HOST: SSHホスト名
# STG_SSH_USER: SSHログイン用ユーザー名
# STG_SSH_KEY: SSHログイン用秘密鍵
########################################################

env:
    # 検証サーバーのデプロイ先パス
    TARGET_DIR: /home/focus-test/www/ouchi.earth/wp-content/themes

jobs:
    Deploy:
        name: サーバーへデプロイ
        runs-on: ubuntu-20.04
        steps:
            - name: 🚚 最新コードの取得
              uses: actions/checkout@v3

            - name: Node.jsをインストール
              uses: actions/setup-node@v2-beta
              with:
                  node-version: '16'

            - name: SSHキーの生成
              run: |
                  mkdir -p /home/runner/.ssh
                  touch /home/runner/.ssh/action_key
                  echo "${{ secrets.STG_SSH_KEY }}" > /home/runner/.ssh/action_key
                  chmod 600 /home/runner/.ssh/action_key

            - name: 📂 サーバーへデプロイ
              uses: easingthemes/ssh-deploy@main
              env:
                  SSH_PRIVATE_KEY: ${{ secrets.STG_SSH_KEY }}
                  ARGS: '-rltgoDzvO --delete'
                  SOURCE: './'
                  REMOTE_HOST: ${{ secrets.STG_SSH_HOST }}
                  REMOTE_USER: ${{ secrets.STG_SSH_USER }}
                  TARGET: ${{ env.TARGET_DIR }}
                  EXCLUDE: '/.git/, /.github/, /.devcontainer/, /.vscode/, .gitignore, .gitattributes, LICENSE, README.md, .eslintrc, .stylelintrc, .prettierrc'
